id: {{ $id }}
email: {{ $email }}
created_at: {{ $created_at }}
manager_name: {{ $manager_name }}
room_number: {{ $room_number }}
date_from: {{ $date_from }}
date_to: {{ $date_to }}
name: {{ $name }}
last_name: {{ $last_name }}
message_admin: {{ $message_admin }}
